service:
  name: sns-publish-lambda

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline
  
provider:
  name: aws
  runtime: nodejs6.10
  profile: serverless
  stage:  ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  role: ${self:custom.config.${self:provider.stage}.ROLE, ''}
  vpc: ${self:custom.config.${self:provider.stage}.vpc, ''}
  environment:
    NOTIFICATION_TOPIC: ""
  
custom:
  serverless-offline:
    port: 5000
  config:
    dev:
      ROLE: ""
      NOTIFICATION_TOPIC: ""
      vpc:
        securityGroupIds:
          - ""
        subnetIds:
          - ""
functions:
    emailNotification:
      handler: app/index.emailNotification
      name: email-notification-api-${self:provider.stage}
      description: "AWS lambda function to publish payload data to SNS topic"
      events:
        - http:
            path: mail
            method: post
            cors: true